---
title: "Overview of basic features of ggplot"
author: "Caleb Trujillo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("nycflights13")) install.packages("nycflights13")
if (!require("gapminder")) install.packages("gapminder")
if (!require("Lahman")) install.packages("Lahman")
```

### Figure 3.13

Here you will make your figure. You can write a commit for each figure or error leading up to the figure that matches. Be sure to include commits of the transitions and name the figures such as "Recreating Figure 3.4" and "Recreating Figure 3.7". Practicing frequent commits is a great habit.

```{r 3.13 plot}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point() 

```

### Figure 3.16
 
Here you will make your next figure.

```{r 3.16 plot}
p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp,
                          color = continent,
                          fill = lifeExp))
p + geom_smooth()
```
